export default {
  fruits: [
      { name: 'apple', image: require('../assets/images/items/fruits/1.png') },
      { name: 'peach', image: require('../assets/images/items/fruits/2.png') },
      { name: 'avocado', image: require('../assets/images/items/fruits/3.png') },
      { name: 'banana', image: require('../assets/images/items/fruits/4.png') },
      { name: 'blackcurrant', image: require('../assets/images/items/fruits/5.png') },
      { name: 'blackberry', image: require('../assets/images/items/fruits/6.png') },
      { name: 'cherry', image: require('../assets/images/items/fruits/7.png') },
      { name: 'mandarin', image: require('../assets/images/items/fruits/8.png') },
      { name: 'coconut', image: require('../assets/images/items/fruits/9.png') },
      { name: 'redcurrant', image: require('../assets/images/items/fruits/10.png') },
      { name: 'gooseberry', image: require('../assets/images/items/fruits/11.png') },
      { name: 'grapefruit', image: require('../assets/images/items/fruits/12.png') },
      { name: 'grape', image: require('../assets/images/items/fruits/13.png') },
      { name: 'plum', image: require('../assets/images/items/fruits/14.png') },
      { name: 'kiwi', image: require('../assets/images/items/fruits/15.png') },
      { name: 'lemon', image: require('../assets/images/items/fruits/16.png') },
      { name: 'lime', image: require('../assets/images/items/fruits/17.png') },
      { name: 'orange', image: require('../assets/images/items/fruits/18.png') },
      { name: 'mango', image: require('../assets/images/items/fruits/19.png') },
      { name: 'watermelon', image: require('../assets/images/items/fruits/20.png') }
    ],
    vegetables: [
      { name: 'apple1', image: require('../assets/images/items/fruits/1.png') },
      { name: 'peach1', image: require('../assets/images/items/fruits/2.png') },
      { name: 'avocado1', image: require('../assets/images/items/fruits/3.png') },
      { name: 'banana1', image: require('../assets/images/items/fruits/4.png') },
      { name: 'blackcurrant1', image: require('../assets/images/items/fruits/5.png') },
      { name: 'blackberry1', image: require('../assets/images/items/fruits/6.png') },
      { name: 'cherry1', image: require('../assets/images/items/fruits/7.png') },
      { name: 'mandarin1', image: require('../assets/images/items/fruits/8.png') },
      { name: 'coconut1', image: require('../assets/images/items/fruits/9.png') },
      { name: 'redcurrant1', image: require('../assets/images/items/fruits/10.png') },
      { name: 'gooseberry1', image: require('../assets/images/items/fruits/11.png') },
      { name: 'grapefruit1', image: require('../assets/images/items/fruits/12.png') },
      { name: 'grape1', image: require('../assets/images/items/fruits/13.png') },
      { name: 'plum1', image: require('../assets/images/items/fruits/14.png') },
      { name: 'kiwi1', image: require('../assets/images/items/fruits/15.png') },
      { name: 'lemon1', image: require('../assets/images/items/fruits/16.png') },
      { name: 'lime1', image: require('../assets/images/items/fruits/17.png') },
      { name: 'orange1', image: require('../assets/images/items/fruits/18.png') },
      { name: 'mango1', image: require('../assets/images/items/fruits/19.png') },
      { name: 'watermelon1', image: require('../assets/images/items/fruits/20.png') }
    ]
}
